<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Jahongirs-MacBook-Pro.local" name="OLB.RubyOnRailsHomePage_TEST" tests="4" failures="0" timestamp="5 Mar 2020 00:59:41 GMT" time="3.685" errors="1">
  <testcase name="validateRubyOnRailsText" time="0.032" classname="OLB.RubyOnRailsHomePage_TEST">
    <error type="java.lang.AssertionError" message="expected [Ruby on Rails222] but found [Ruby on Rails]">
      <![CDATA[java.lang.AssertionError: expected [Ruby on Rails222] but found [Ruby on Rails]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at OLB.RubyOnRailsHomePage_TEST.validateRubyOnRailsText(RubyOnRailsHomePage_TEST.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- validateRubyOnRailsText -->
  <testcase name="validateSignIn" time="0.082" classname="OLB.RubyOnRailsHomePage_TEST"/>
  <testcase name="validateSignUp" time="0.110" classname="OLB.RubyOnRailsHomePage_TEST"/>
  <testcase name="launchBrowser_URL" time="3.461" classname="OLB.RubyOnRailsHomePage_TEST"/>
</testsuite> <!-- OLB.RubyOnRailsHomePage_TEST -->
